[master]
node1 ansible_host=192.168.1.12
node2 ansible_host=192.168.1.15
node3 ansible_host=192.168.1.25

[workers]
node1 ansible_host=192.168.1.12
node2 ansible_host=192.168.1.15
node3 ansible_host=192.168.1.25

[all:vars]
ansible_user=orangepi
